project commit
made-ml-in-prod-2021/agafonovartem pull request #2
Opened 2021-05-08 22:45 UTC by agafonovartem

Methods: logreg + tree from sklearn with parameters
Transformers: std scaler, PCA, squared features (custom)
Validation: train test split, k-fold cv
Pipelines: train (e2e), predict (named test)

**Criteria**:
-2) ✓ 1
-1) ✓ -
0) ✓ 2
1) ✓ 2
2) ✓ 2
3) ✓ 2
4) ✓ 3
5) ✓ 3
6) ✓ 3
7) ✓ 3
8) ✓ 3 (src/custom_transformers/squared_features)
9) ✓ 3
10) ✓ 3 ( функция называется predict_model; пайплайн, принимающий на вход сохраненные модель и трансформеры, записывающий предикаты в папку запускается так: python src/test_pipeline.py configs/config_test.yaml  ) 
11) × 0
12) × 0
13) ✓ 1
______
31

2021-05-10 11:35 UTC, sonomama commented on ml_project/tests/configs_data/config_feature_params.yaml
> +    - "MSZoning"
в ридми написано, что задачка про heart disease, а здесь почему-то другая?

2021-05-10 11:35 UTC, sonomama commented on ml_project/tests/datasets/generated_dataset_sample.csv
> +Age,Sex,Target
а для чего этот файл генерится? он еще и другого формата, чем оригинальный

2021-05-10 11:35 UTC, sonomama commented on ml_project/tests/features/test_features.py
> +@pytest.fixture
насколько я поняла из своего ревью все фикстуры лучше держать в conftest.py и еще лучше scope указывать, чтобы по несколько раз не вызывались, вот [тут](https://habr.com/ru/post/448786/) хорошо написано

2021-05-10 12:43 UTC, agafonovartem commented on ml_project/tests/datasets/generated_dataset_sample.csv
> +Age,Sex,Target
Он генерит тестовый датасет.  Пайплайн подходит для многих задач классификации. Формат .csv, как и у оригинального датасета heart.csv

2021-05-10 12:53 UTC, sonomama commented on ml_project/tests/datasets/generated_dataset_sample.csv
> +Age,Sex,Target
У меня практически нет опыта написания тестов, но показалось, что немного неожиданно брать тестовые данные совсем отличные от оригинальных. Потому что для того, чтобы такой новый датасет обработать все равно нужно дополнительный код написать, указать какие фичи категориальные или численные. Нужно ли плодить сущности, когда можно сгенерировать нечто похожее на оригинальные данные? Но это не камень в ваш огород, сама пытаюсь понять как правильно делать :)

2021-05-10 13:09 UTC, sonomama commented on ml_project/src/enities/model_params.py
> +    print(model_params_dict)
здесь print точно нужен?

2021-05-10 13:20 UTC, sonomama commented on ml_project/src/enities/_test_pipeline_params.py
> +    input_data_path = yaml_dict.get("input_data_path")
Вижу, что у вас много где get используется для считывания yaml. Мне показалось, что в примере, который нам дали, было попроще. То есть можно создать
`marshmallow_dataclass.class_schema(_TestingPipelineParams)` и вызвать метод `load(yaml.safe_load(input_file))` чтобы вернуть все параметры. Если вы намеренно не стали так делать, то disregard that :)

2021-05-22 18:18 UTC, Mikhail-M requested changes
удалите .venv

2021-05-25 20:04 UTC, agafonovartem commented
удалил

2021-06-01 08:42 UTC, Mikhail-M approved these changes
Баллы: 31

2021-06-01 09:07 UTC, merged

2021-06-02 11:51 UTC, sonomama commented
Ревью сделала, апрув не успела поставить из-за отсутствия коммуникации. Но с баллами согласна.