Homework3
made-ml-in-prod-2021/agafonovartem pull request #4
Opened 2021-06-09 19:01 UTC by agafonovartem

1) 5
2) 10
3) 5
3а)  3
4) 0
5) 5
6) 0
7) 0
8) 0
9) 1
---
Итого 29 баллов

2021-06-10 06:37 UTC, ningeen commented
> Чтобы получить баллы сделайте скриншоты списка всех дагов и каждого графа(в исполненном без ошибок виде) по отдельности и прикрепите их в описание пулл реквеста.

2021-06-10 06:58 UTC, ningeen requested changes
Оценка: 5+8+5+2+5+1=26 в случае, если будут скрины дагов и инструкция к запуску

2021-06-10 06:58 UTC, ningeen commented on airflow_ml_dags/dags/dag_predict.py
> +_predict("data/processed/2021-06-09/test_data.csv", "models/2021-06-09/model.pkl", "abiba")
вот это удалить

2021-06-10 06:58 UTC, ningeen commented on airflow_ml_dags/dags/dag_predict.py
> +    )
Лучше использовать FileSensor

2021-06-10 06:58 UTC, ningeen commented on airflow_ml_dags/dags/dag_train.py
> +    )
Лучше использовать FileSensor

2021-06-10 06:58 UTC, ningeen commented on airflow_ml_dags/dags/dag_train.py
> +TEST_SIZE = 0.2
Лучше убрать в конфиг

2021-06-10 06:58 UTC, ningeen commented on airflow_ml_dags/dags/dag_train.py
> +    [data_sensor, target_sensor] >> train_test_split_ >> train_model  >> validate_model
Вроде просили как минимум 4 стадии, тут 3 + сенсоры

2021-06-10 06:58 UTC, ningeen commented on airflow_ml_dags/docker-compose.yml
> +    command: -c 'airflow db init && airflow users create --username admin --password admin --firstname Anonymous --lastname Admin --role Admin --email admin@example.org'
Вроде для работы сернсоров тут надо прописать `&& airflow connections add fs_default --conn-type fs`

2021-06-12 11:49 UTC, agafonovartem commented
<img width="1034" alt="Снимок экрана 2021-06-12 в 14 39 52" src="https://user-images.githubusercontent.com/60934311/121774914-56adf380-cb8d-11eb-9e3e-bcf12155332c.png">
<img width="2304" alt="Снимок экрана 2021-06-12 в 14 39 32" src="https://user-images.githubusercontent.com/60934311/121774916-57df2080-cb8d-11eb-912e-817dae71805b.png">
<img width="2290" alt="Снимок экрана 2021-06-12 в 14 39 05" src="https://user-images.githubusercontent.com/60934311/121774917-5877b700-cb8d-11eb-8a95-ee699dde470c.png">
<img width="2322" alt="Снимок экрана 2021-06-12 в 14 38 52" src="https://user-images.githubusercontent.com/60934311/121774919-59104d80-cb8d-11eb-8534-221fc59fa876.png">

2021-06-12 11:50 UTC, agafonovartem commented
> Оценка: 5+8+5+2+5+1=26 в случае, если будут скрины дагов и инструкция к запуску

какая инструкция к запуску вам нужна? чего не хватает в ReadMe?

2021-06-12 13:23 UTC, ningeen commented
Какие переменные окружения добавить. И переменные в airflow

2021-06-15 18:28 UTC, agafonovartem commented
> Какие переменные окружения добавить. И переменные в airflow

добавил см readme.md

2021-06-18 07:55 UTC, Mikhail-M approved these changes
Баллы: 29

2021-06-18 07:55 UTC, merged